profile: view

ceip_policy_disclosed: true

shared:
  ingress_domain: view.20-249-58-222.puyopuyooceanviewpro.com
  activateAppLiveViewSecureAccessControl: false

contour:
  infrastructure_provider: azure
  contour:
    configFileContents:
      accesslog-format: json  
  envoy:
    service:
      type: LoadBalancer
      loadBalancerIP: 20.249.58.222      
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-resource-group: northernlight-view

tap_gui:
  service_type: ClusterIP
  app_config:
    backend:
      database:
        client: pg
        connection:
          host: ${TAP_GUI_DB_SERVICE_HOST}
          port: ${TAP_GUI_DB_SERVICE_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: "b3de4d18a30e48a0b190"
            clientSecret: "a21c608f86802ef51253cb22819506ed3924ecd1"
    kubernetes:
      serviceLocatorMethod:
        type: multiTenant
      clusterLocatorMethods:
      - type: config
        clusters:
        - url: https://northernli-northernlight-ru-c6535d-vrpb6cvu.hcp.koreacentral.azmk8s.io:443
          name: run
          authProvider: serviceAccount
          serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6Im5sWUVfUHBqdHhRb1FGQ3FvbG43WFRhRzFwdDBlbTRhNlNSd1hqNlNyR1kifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNzg3YWJhODUtYjA4Ni00ODg1LTgzYzMtNzZjNTA2YjBkOWFhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.fr1-7M-xI-ifjAYtFvJKia6bagal9nh8mB2IJzqegBtHdWBa3mZtfAup9mXOg3ZWQ7WGCyxsJD5Ab7rdIOgfACjXAiOqygHdkTiLVFSzR9B6hOlDyxBpo2up4UJL7DC7f9rQuSnC8U0I4VgbB5w3oejPwPKlDd2v2eIYAHS9rXZ-_FAhp4P2tz55cQi29io79Ce4cfb1016YmN9OzvEj9gj8Y53px9VqINUhP_z3amPVjABWt91zymZciBpovW33XWFqXHGvbAfqw8ntTwZoJabIRDWoQFXZ64D-MAsr36_pbYfSTtYOh_xjglNmFgJXN58xPICmNAtx14XL9pEvh7lHsXnJXmxFbcWufQxTiNGEwxDMroCFJmm02JKctrCf_0CPhvQqCgQz6xhiezBbRinF8gnjvGYxS-eaE-CI4_JsYY9-WesZZ8A3KABG_lHcbkX1Nkd6JqYC2qaxxptYbOTKX14HivUOY7DPBcQkXeDGzcRmJmHaXNOxobOPCPQqGQ5xY56u-9CgkEDAynH8w4YFnLnGlWcpSQPKP_j9p3EVIYIXuk7gDad8vEk5pqefuLTIDYBsiiA7bv7Gm8X_s4-hUdMmjWs1GwtUKYmo6smAmVn8Wk3YGxuhpXBtNh9r_sG0cQJl13hwc9O-2YqXCia9rm80L36BPMbTddJOfP0
          skipTLSVerify: false
          caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQXRDZ0F3SUJBZ0lRYzdqQnJRelFDcGM1OU9lUDV3dmJxVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWdGdzB5TXpBNU1Ua3dOREEwTlRCYUdBOHlNRFV6TURreE9UQTBNVFExTUZvdwpEVEVMTUFrR0ExVUVBeE1DWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUURGCks2dG1KdVdzMHZiVjVzaGh1ODRuNzZzbnBVVXNNQ0QrcmpqV0FENGdBNXlNRXFCSUtHRFU5V0VBTWtyb2dZc0EKd2hDV3gzdDhzaWJiK3J0TlhDWG5nU2dMY25sM0JiMmVKMDR5TUxOOTJKN3hIMXRhNlpjbWYxZFVqVVB3QzREZApIeXYrM1JrTlBwd1FMS0FNdGNiS2UrRTFoaHEwMC9SVHhKUkFuN3dOVnEzMW9SK0RFVFVkNTkxRVhvZ2NOMVl0CkJKaStVU2E0TFNRMmk3R0dkQmM5U2FuM3NPQmlOZUdaZUlGMkdReEs5MW9jVks3R3V4enFub1EwclJ5SmQvaWsKQmlpd056NVRNb21jL0wrcFprZy9PaDdCMS9WSXZ1N0lLZ1FQZWJwVEd0ZWg1U2JJaVJFTmlrYUtLTTVJLzFJcgpQeko1OWlqZG9yWkJzV2xSRFpBZE5XOXVSZWJ5RzA3c296dGdEM3ppMmtkZ2lHclQySitPdS81N2tuRlZqOHB2Ck1vTWd0azZiTjFmbVJ3NkFwOG5ER05uallORnhQUTg4OGVKUk91QmFkYmFPSy9zMnJRN3krS1BDLzJGeE1zNWUKK25MdzdzdTZXdmpWbTZ3VVZ0NDNnSTNERGZyRmRCWHM2a05Ldkt0bmFicGoyR3BuaktWdXhBd1VJR25aUW1qOQp0UURNMEVmeCs2cTRBQWxwTkNaMTluQlBYTnVkam1nVUhoRG92aHB4ckFFVHRxM1crOExhTzF4ZDRUT2FhOHV4ClZOYUxYc3FqT3hSbWVXVitqRkVERGVLVDZ6Qi90ZUJjdmd5elhPNmhyUnV1T2hXazgwOEwxcENFVmp1NWRSK3kKaCtTVlVheHUyMzh0Ly8vODJFRDBlaE16U3dKQ0FRRHUvbTNQRU5IRDNRSURBUUFCbzBJd1FEQU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVJY1NVYXFqUjVza2VBNzI4CjdoU0FhM1lIeVlzd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFDK2t4aS9yUUxMSmM3cDhMOTRMWFhKY3BBQUcKZlhLTnNsSUlEanZMOHRJTVo4TnBROTMxUkRRVFlMK3ZEckNHbDFGYTBkZVVvRml3MFFZY0pqbkRhZk05aTlBUQoySzZjZ2toMUlUK1pKQ0hlWktZSDh2M3MrUEk0RWU5U0J6bkZUQ1BTTnk5ZS9Dby9Zci9OcVZmQXdSdGtwNjdhCnU0bHNXRnA0VXh0Ti9uaTluZ2d6Tmx0c3NZdXo4Z2c5VjFER2Q2SkJSRVZaMHp4Rkg1WEFBMHhZT3ZjVWd5ZE0KMzlZOHpjRkYvTXBGa2RkbTB4em1scjA5YnQ0bWlEOWY0S0tFdXlTbjhQZnNpMzJ5ZDlWOFlVTW1tVU51ejBqcwozbzRGdW9GM2ZJZ2NuTWpTbkpkSDQ0ZGh3a3dybjBSZjduSEs1UjQ4Q1ZXaU95ckM5SjNhWW5xZmJBSXg4QmJnCndHak8yM252TGVhdHNMU1JYektwdXhpazdnS09HZnljQVMzY1crM2FwVDNJRWpSSGxDVS9kd1JNdEJRcmdkL3gKb0JxZDU3Y1c3K1ptZGJOc1hyM3pud2RCR05TSVM3MUFyQXRDRXBHWHo4MlFZMzhVSC9yTGlSTHgxNGY2WDFQagphcHRzdGhicG11Z05SSSt2SE5XUC8zbjd1bjhHS2M2Zlp3d0E2Mkt4RHJhWGFKWmh3VmpFSndyVGp4c2hBOXY4CmhNMTdwRGJDK0hZbWVXTGNwZVo3Vm1iZWYvOGtjM0lsbGN1UGtnTmRSSDM1NkRUVXhpekUyS2dycjUrMHBaV0YKV2pHeHBJU3p3bEpYT0xyY2RrbjgwTjZ4c0pkamlodGVZaU5hZy9WZGtlMTRwdUVzbHQxZFNXajFSL1lFVUljZApjQXh1b2VPQlViV2tlMDZ4Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      - type: config
        clusters:
        - url: https://northernli-northernlight-bu-c6535d-r9uy33wu.hcp.koreacentral.azmk8s.io:443
          name: build
          authProvider: serviceAccount
          serviceAccountToken: eyJhbGciOiJSUzI1NiIsImtpZCI6IlFRajBXVHhDR3VGQ0pVdVJCMGVqWVdUUVhHYWtxWDBidVZsalhNaEdEbm8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJ0YXAtZ3VpIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6InRhcC1ndWktdmlld2VyIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNGMwODEyMDktMTI5OS00ZWM0LTlmMWItNDMyMDhhOTU4NjVhIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OnRhcC1ndWk6dGFwLWd1aS12aWV3ZXIifQ.Z0YETUIQamsXJWjABaWyaQLNQ5ottrHNKP2KRRtGxgMhEpOvGOjuOyp-TYMojg3cPxP77-cB7IMhjl48MjduNfTTGnt1cL69Yw2wIpZzbFUaM8UZ_74_VtlLwWISEd3-n-OofnctMeg5xXLc909TXrjFbElXHp9Ww9S-FZ0mE1T5J8C8hs4n2CIE99EnNWOcW1kfxfP2arCUwb7CzjpSqj2daoktaPCPCR935cX5JH0YInbDh6ZdKyAz6jDmnt6TXn15HhuWQWqIDSU1p5TGvEczvnOla-5T7iVPbE3UEDYWzCZJAamlXWS1Fyb_IFnL7FxsYXT_IUsAgZoFEYnp6RskTluWbciMRgkGtk-bnOM_UD1WXnMM9DE7ME4u8ob1ASTdmjxyJDztMVNL7gxUT9vBs6PHhdOK3NfYT460HFmg_-WZN7wn6Z8iN9Enk500qATMk170vrTVE7BoV3xCqD9ZkyjpmB9JGoIjINOJD5Jy7512RMrFOExx0fYntao-9yDEs8ix2asIGGciaoJTMFRVuXx27Mkc65pGwNzLwjPIjLHjMVdxch5eD-tWlm0UPUUA8Y-TRo1lkTK1aO6oYSurodNWPMGJDLyVoyLokeIll-C17GeKDjTq86bQTfIKJdHsGZOXi-T6m4ylycK0tlchUL5OuGaXqEb2Z_uGAhU
          skipTLSVerify: false
          caData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQXRDZ0F3SUJBZ0lRWWsxY3QzUDVxWmZoZHlOeDN0K2ozREFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWdGdzB5TXpBNU1Ua3dNelUxTURoYUdBOHlNRFV6TURreE9UQTBNRFV3T0ZvdwpEVEVMTUFrR0ExVUVBeE1DWTJFd2dnSWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUNEd0F3Z2dJS0FvSUNBUUMrCkhlV3dkKzJZMU5Za3BKWmkxQmJzR3hBWHlaWVUrbHdwZVVoYTdZUStaTHE4Z2VMNTZlZVJFU0JMc2N4cGxyS1cKR2htSDBHOGJxYW9VSS9rN2JsSXNmcmJyTDltMnA3R083bTY1K1JnNVovcmpJUVNxSmV0Mk9NL3dvMzFpamJhbApnaFNzanZCVlV3NW5OMmlNTkM5OXpsU0Jub1NMVUVNY0tHdTh5eUtGT1FUcXRrZFZFQjZmUkYrUDUxN1A5Zi81CkNPZWNRVU9wUkUxNVZDZGRvQzJjTlRQa0h0L1pJM3hxME1HdU5HcWtOZVlnTlREbkszZEx4cHFRWmFkYzFUMHEKQ2dZbmllOWIvUTV0TmhibTR4d2tiYi9yNDdyNkFPbUxBdktDcDlYQytQQ3kvWGk5dmpORzczY0hWVXhzZE1CbAp3OElUcjM3VWlQTVcwQnVnTm41K3VYLzJLYS9QMEpnV0FSOGdudzg0Rlg2UFYwbFJId1laTGRmYmJBMnRZZmVaCnovUVZISjQyd0hRYVRsNXdUUCtXS3ZpdEMveGpNVjVUWXlSUFVkNDZ1dVUvdmphbFNGWUJSb3E0dnp3Vk02THAKbG5GZU8yVXNmSEh1cm5vaDF6TEVaMThodmtMaUdpSDhPZWxkM0x5MUkwckpDTHJBMzVxa05GRklHK0RkOWRQTgpqZG5STFpFM0FUeXlrQjl3UUgyRGVTODRUK3pFeFJsWm9DNkFCTU4rYTJ4UmRCeFhsMWZ6RTBVNkhOYVBJRDc4CmNrT3ZMa0xETHJuanVOYUVlZzYvTjR1TXVSV1FFeWFQVWlRRFo3Yll5dk9GRGlQeWp4NGE4d3NncDNzbDZHbk4KSXRZL0pxMy94Q1Yycm1USmdua2NTNjhOaW1VTTJEVHBmUnlBQm1wNFB3SURBUUFCbzBJd1FEQU9CZ05WSFE4QgpBZjhFQkFNQ0FxUXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVteERLT25CbmxQTmJLaTNWCjZ0V005akw4TGMwd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dJQkFDQ05QT2VUOVUrR0QyMFAzc1BxNGdYR1ZsQlkKaEhYWVVhdEMyRWxIejJwN1NsbjhOMmkrRW44OFRHQ29BVTdIcTYzMzErUWVMMUZ4cDk3U25Uall6c1pIRXVjMgpzNEpOdHhzOHFUY2lTTTJRNmYyLzdoVzg2RW5lSnljUHVkck95RVQrNitncVRqcWE2c1hFaVl4RTZRTHo5WEdJCjBrY2tjYWRuNk9EUlFqWHNMVm5rbExjWlg4ZG5RbFI3clNkSytma2N3OVVPaHNIaEkrSXp6TzFPV3E5aDBYSGQKaEJhVi9lVmFvenJRWi85UHl3Yy9BOGRVdFRzeFBxK0M3UEJxVEh3RUFPdWNnSmxOMS8zS0RpSFN4em15UGNrSApLRjVFMDh3U0JRak1uaEhBVEhhUzc0T2x0djFNM0VRVmN0K1poZkFZT2o2SFVwdEVRcXZWKy9jMXJPaUU1aURKCmhSQkd0VFYrbmpRSmJyNTUyc3ZaSkdzZ2lUZ3ByOElkSEg2b3pJTkxzQVhkcmlWZ1pmZUxsNGpxbGx2YXFYcmsKcnZUeDJ3eHNzNnNUWGxOWDE5b0ZrM0ROanpyN3ZmeFpaR1RHa1BheUZQMEZhVzZaWnVrM256VklMTGFDaEh6Lwpobk5vTWhHZitKSFcvMjRydlZWclIxRmxIeDZtU3RlL0xNMlVTbWI2enRlQUxyWEdYQng2cmplSGhib2R1cnVaCmpwUFY5WWkzSTEzSDNHZFZmLytmeXpQNUI3VEE3eSsrMkM3VG1UT0lSUlk1ZFNWL1JCeUN5SFM1bTRFQ0VLNTEKL0VxRTBHNjduOXV4OG40dUs0ODZJOWp2bUY4Z05WTEh4UTkySktTZGozOXhzWUhwR0VKSXBTUmRUV3pJa1JmZwphSS9GdWVoaVVGWjZSOXlkCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    proxy:
      /metadata-store:
        target: https://metadata-store.view.20-249-58-222.puyopuyooceanviewpro.com/api/v1 
        changeOrigin: true
        secure: false
        allowedHeaders: ['Accept', 'Report-Type-Format']
        headers:
          Authorization: "Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6InJVMHNldFRmajU1Z2QwcnpET1ZEbWlxMERtV1FUQUNhd1puR2ZBd1hnTHcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJtZXRhZGF0YS1zdG9yZSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJtZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjVhMjJiOGVmLTRlMDItNDFhMC1hOTllLWYyYzY4OGYxOWUyMCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDptZXRhZGF0YS1zdG9yZTptZXRhZGF0YS1zdG9yZS1yZWFkLXdyaXRlLWNsaWVudCJ9.YjM5kjbsh6v7kHHgfaqQEZ01v_oWlKePsy0T7nCJmyhg7shwRWO5XGk15UlTQaOTNO79Znc7S-c4w595R8YUrbZJfv0xiH3QMo-lWFBPQCbbQQYkTnsdyrfw3ku7osTCISeHaPn8EMcYcIXJBleD35JZnD5HhPEgPu9SG3d3IVOeW3oQXbZB9319q73D3_GLx29CveZLepsIQHkGRNzMSirGBiIOPsQdt5ghcFxqkV6MkkUGCVoZQ7u2nIAcMOPapcBC8QxzFpNKz3d2yB4t0N82Lhvyi8OBcLnynHVlGYgQDi3zH0vLSevqp4IUuQBDqLxam6mCasCFDQlILQTcQ8OmFFKe2wr2zKdJLR_TjXSJGDiQcrab9g4hKYzDGOLGt36WDxvNByyfvlpyMyHOwiqtj__NaODk0wpLc4DdEjpS-EqBOX30xHbOETbYj-QH4Zj4ZNrM52sesBGaxzOzfCrNjhOr4fkNvokAe0xVA2K9_6v5YeEP4c5JviXsU2-w5Ukxk1qwhoA8aJn1eWAyeWmfx_6aHFZiIu5vXuxiqxq-_gC-1z__4mJ0nS2pDX808VQSR9JUX68UDiXzYt7ySevsi2aXcoqzD-mGW74qSLKNde6IzmAYZLHUqIMjpmiLLl55Cp3WZrfUoqQpoLIuM_ZUCggltyCkg4DdQVkGZog"
          X-Custom-Source: project-star

appliveview:
  ingressEnabled: true
  sslDeactivated: false

accelerator:
  ingress:
    include: true    
    enable_tls: true  
  tls:
    secret_name: tap-default-tls
    namespace: tanzu-system-ingress

metadata_store:
  ns_for_export_app_cert: "*"

package_overlays:
- name: contour
  secrets:
  - name: contour-default-tls
- name: tap-gui
  secrets:
  - name: tap-gui-db
- name: metadata-store
  secrets:
  - name: metadata-store-read-only-client

excluded_packages:
- learningcenter.tanzu.vmware.com
- workshops.learningcenter.tanzu.vmware.com
- api-portal.tanzu.vmware.com
