profile: run

ceip_policy_disclosed: true

shared:
  ingress_domain: run.20-249-58-38.puyopuyooceanviewpro.com
  ca_cert_data: |
    -----BEGIN CERTIFICATE-----
    MIIDQTCCAimgAwIBAgIUbReTzElGl6M6i2dDJbuXDHA6SwUwDQYJKoZIhvcNAQEL
    BQAwMDETMBEGA1UEAwwKZGVmYXVsdC1jYTEMMAoGA1UECgwDVEFQMQswCQYDVQQG
    EwJKUDAeFw0yMzA5MTkwNzM1MTVaFw0zMzA5MTYwNzM1MTVaMDAxEzARBgNVBAMM
    CmRlZmF1bHQtY2ExDDAKBgNVBAoMA1RBUDELMAkGA1UEBhMCSlAwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDGadGYcyo77a6rWfKoa0Ne+NVMtH4ieFmd
    YxmUQKaT03Cs+kIj4uusb6G2aYGMAZ1EKh4gbm/ozlDMrfitPa0PMXvVL/b4/XBQ
    +u0TgVtzEntmihPQa9YtjdXF58sD1CvGs38X9GqNXGetFY6BXeUior6iAeqB9DcB
    rTokCYftnVXwBqEMotfZ/rMeoa9uNUrUj3xcerIFnzZot6f8bPNKGfmG6nm6DeOl
    /t7KXO5xsR9fjkyGxhK8i74oyuZ6rp0E2jG9eqcxnXERTOWbMJJFXyIhMN74t4L5
    oaZQbMyuO2ucyRjsKDOJcSBeDhUu2MsZgrR26EnCvGXMxrk4truLAgMBAAGjUzBR
    MB0GA1UdDgQWBBSxIBOP9pBYZa8bP78Rck8acIRypjAfBgNVHSMEGDAWgBSxIBOP
    9pBYZa8bP78Rck8acIRypjAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
    A4IBAQB+oAd6Ljrh3n+/x83qBpb5i5IWdmWPRuhtrdx4Gu2dUYpUGmZu53yvaBr9
    N6+GOEAApOReoT334znkDkmW+B/pYak8s7Jv+QfOs1LaXktDdIIonuiyU6CrsJh+
    kBrzXdB56COyqE/RFFL6l6vlq76+3gIPFeJlFMGlUosexiRSc51clpxMMwhnSgW3
    +d7ecwSBMWrmc3PDZ2Itmiw6xhAWgeo6+WEH7xEhN5h1GrJrzaO3D7b2OZJLGyp6
    caFlZLECMjJBBhDny7RBwOnKus1+NnUpwq5L5d+4PFzZkFh5F2jITP60CWCwIqzD
    +d7ARNH63fgoQ3dq0clbcWbvfO/h
    -----END CERTIFICATE-----

contour:
  infrastructure_provider: azure
  contour:
    configFileContents:
      accesslog-format: json  
  envoy:
    service:
      type: LoadBalancer
      loadBalancerIP: 20.249.58.38      
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-resource-group: northernlight-run

cnrs:
  domain_template: "{{.Name}}-{{.Namespace}}.{{.Domain}}"
  default_tls_secret: tanzu-system-ingress/tap-default-tls

appliveview_connector:
  backend:
    ingressEnabled: true
    host: appliveview.view.20-249-58-222.puyopuyooceanviewpro.com

api_auto_registration:
  tap_gui_url: https://tap-gui.view.20-249-58-222.puyopuyooceanviewpro.com
  cluster_name: run

accelerator:
  ingress:
    include: true    
    enable_tls: true  
  tls:
    secret_name: tap-default-tls
    namespace: tanzu-system-ingress

package_overlays:
- name: contour
  secrets:
  - name: contour-default-tls
- name: cnrs
  secrets:
  - name: cnrs-https

excluded_packages:
- image-policy-webhook.signing.apps.tanzu.vmware.com
- eventing.tanzu.vmware.com
